// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LoginInfo.proto

package eu.hellek.gba.proto;

public final class LoginInfoProtos {
  private LoginInfoProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface LoginInfoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required bool loggedIn = 1;
    boolean hasLoggedIn();
    boolean getLoggedIn();
    
    // optional string loginUrl = 2;
    boolean hasLoginUrl();
    String getLoginUrl();
    
    // optional string logoutUrl = 3;
    boolean hasLogoutUrl();
    String getLogoutUrl();
    
    // optional string emailAddress = 4;
    boolean hasEmailAddress();
    String getEmailAddress();
    
    // optional string nickname = 5;
    boolean hasNickname();
    String getNickname();
    
    // repeated .colectivos.LoginInfo.UserFavouritePositionProxy favourites = 6;
    java.util.List<eu.hellek.gba.proto.LoginInfoProtos.LoginInfo.UserFavouritePositionProxy> 
        getFavouritesList();
    eu.hellek.gba.proto.LoginInfoProtos.LoginInfo.UserFavouritePositionProxy getFavourites(int index);
    int getFavouritesCount();
    java.util.List<? extends eu.hellek.gba.proto.LoginInfoProtos.LoginInfo.UserFavouritePositionProxyOrBuilder> 
        getFavouritesOrBuilderList();
    eu.hellek.gba.proto.LoginInfoProtos.LoginInfo.UserFavouritePositionProxyOrBuilder getFavouritesOrBuilder(
        int index);
  }
  public static final class LoginInfo extends
      com.google.protobuf.GeneratedMessage
      implements LoginInfoOrBuilder {
    // Use LoginInfo.newBuilder() to construct.
    private LoginInfo(Builder builder) {
      super(builder);
    }
    private LoginInfo(boolean noInit) {}
    
    private static final LoginInfo defaultInstance;
    public static LoginInfo getDefaultInstance() {
      return defaultInstance;
    }
    
    public LoginInfo getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return eu.hellek.gba.proto.LoginInfoProtos.internal_static_colectivos_LoginInfo_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return eu.hellek.gba.proto.LoginInfoProtos.internal_static_colectivos_LoginInfo_fieldAccessorTable;
    }
    
    public interface UserFavouritePositionProxyOrBuilder
        extends com.google.protobuf.MessageOrBuilder {
      
      // required double lat = 1;
      boolean hasLat();
      double getLat();
      
      // required double lon = 2;
      boolean hasLon();
      double getLon();
      
      // required string name = 3;
      boolean hasName();
      String getName();
      
      // required string key = 4;
      boolean hasKey();
      String getKey();
    }
    public static final class UserFavouritePositionProxy extends
        com.google.protobuf.GeneratedMessage
        implements UserFavouritePositionProxyOrBuilder {
      // Use UserFavouritePositionProxy.newBuilder() to construct.
      private UserFavouritePositionProxy(Builder builder) {
        super(builder);
      }
      private UserFavouritePositionProxy(boolean noInit) {}
      
      private static final UserFavouritePositionProxy defaultInstance;
      public static UserFavouritePositionProxy getDefaultInstance() {
        return defaultInstance;
      }
      
      public UserFavouritePositionProxy getDefaultInstanceForType() {
        return defaultInstance;
      }
      
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return eu.hellek.gba.proto.LoginInfoProtos.internal_static_colectivos_LoginInfo_UserFavouritePositionProxy_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return eu.hellek.gba.proto.LoginInfoProtos.internal_static_colectivos_LoginInfo_UserFavouritePositionProxy_fieldAccessorTable;
      }
      
      private int bitField0_;
      // required double lat = 1;
      public static final int LAT_FIELD_NUMBER = 1;
      private double lat_;
      public boolean hasLat() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public double getLat() {
        return lat_;
      }
      
      // required double lon = 2;
      public static final int LON_FIELD_NUMBER = 2;
      private double lon_;
      public boolean hasLon() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public double getLon() {
        return lon_;
      }
      
      // required string name = 3;
      public static final int NAME_FIELD_NUMBER = 3;
      private java.lang.Object name_;
      public boolean hasName() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getName() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (com.google.protobuf.Internal.isValidUtf8(bs)) {
            name_ = s;
          }
          return s;
        }
      }
      private com.google.protobuf.ByteString getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8((String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      
      // required string key = 4;
      public static final int KEY_FIELD_NUMBER = 4;
      private java.lang.Object key_;
      public boolean hasKey() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public String getKey() {
        java.lang.Object ref = key_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (com.google.protobuf.Internal.isValidUtf8(bs)) {
            key_ = s;
          }
          return s;
        }
      }
      private com.google.protobuf.ByteString getKeyBytes() {
        java.lang.Object ref = key_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8((String) ref);
          key_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      
      private void initFields() {
        lat_ = 0D;
        lon_ = 0D;
        name_ = "";
        key_ = "";
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;
        
        if (!hasLat()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasLon()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasName()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasKey()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }
      
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeDouble(1, lat_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeDouble(2, lon_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          output.writeBytes(3, getNameBytes());
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          output.writeBytes(4, getKeyBytes());
        }
        getUnknownFields().writeTo(output);
      }
      
      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
      
        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeDoubleSize(1, lat_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeDoubleSize(2, lon_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(3, getNameBytes());
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(4, getKeyBytes());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }
      
      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }
      
      public static eu.hellek.gba.proto.LoginInfoProtos.LoginInfo.UserFavouritePositionProxy parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static eu.hellek.gba.proto.LoginInfoProtos.LoginInfo.UserFavouritePositionProxy parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static eu.hellek.gba.proto.LoginInfoProtos.LoginInfo.UserFavouritePositionProxy parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static eu.hellek.gba.proto.LoginInfoProtos.LoginInfo.UserFavouritePositionProxy parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static eu.hellek.gba.proto.LoginInfoProtos.LoginInfo.UserFavouritePositionProxy parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static eu.hellek.gba.proto.LoginInfoProtos.LoginInfo.UserFavouritePositionProxy parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static eu.hellek.gba.proto.LoginInfoProtos.LoginInfo.UserFavouritePositionProxy parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static eu.hellek.gba.proto.LoginInfoProtos.LoginInfo.UserFavouritePositionProxy parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static eu.hellek.gba.proto.LoginInfoProtos.LoginInfo.UserFavouritePositionProxy parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static eu.hellek.gba.proto.LoginInfoProtos.LoginInfo.UserFavouritePositionProxy parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      
      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(eu.hellek.gba.proto.LoginInfoProtos.LoginInfo.UserFavouritePositionProxy prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }
      
      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements eu.hellek.gba.proto.LoginInfoProtos.LoginInfo.UserFavouritePositionProxyOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return eu.hellek.gba.proto.LoginInfoProtos.internal_static_colectivos_LoginInfo_UserFavouritePositionProxy_descriptor;
        }
        
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return eu.hellek.gba.proto.LoginInfoProtos.internal_static_colectivos_LoginInfo_UserFavouritePositionProxy_fieldAccessorTable;
        }
        
        // Construct using eu.hellek.gba.proto.LoginInfoProtos.LoginInfo.UserFavouritePositionProxy.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }
        
        private Builder(BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }
        
        public Builder clear() {
          super.clear();
          lat_ = 0D;
          bitField0_ = (bitField0_ & ~0x00000001);
          lon_ = 0D;
          bitField0_ = (bitField0_ & ~0x00000002);
          name_ = "";
          bitField0_ = (bitField0_ & ~0x00000004);
          key_ = "";
          bitField0_ = (bitField0_ & ~0x00000008);
          return this;
        }
        
        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }
        
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return eu.hellek.gba.proto.LoginInfoProtos.LoginInfo.UserFavouritePositionProxy.getDescriptor();
        }
        
        public eu.hellek.gba.proto.LoginInfoProtos.LoginInfo.UserFavouritePositionProxy getDefaultInstanceForType() {
          return eu.hellek.gba.proto.LoginInfoProtos.LoginInfo.UserFavouritePositionProxy.getDefaultInstance();
        }
        
        public eu.hellek.gba.proto.LoginInfoProtos.LoginInfo.UserFavouritePositionProxy build() {
          eu.hellek.gba.proto.LoginInfoProtos.LoginInfo.UserFavouritePositionProxy result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }
        
        private eu.hellek.gba.proto.LoginInfoProtos.LoginInfo.UserFavouritePositionProxy buildParsed()
            throws com.google.protobuf.InvalidProtocolBufferException {
          eu.hellek.gba.proto.LoginInfoProtos.LoginInfo.UserFavouritePositionProxy result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(
              result).asInvalidProtocolBufferException();
          }
          return result;
        }
        
        public eu.hellek.gba.proto.LoginInfoProtos.LoginInfo.UserFavouritePositionProxy buildPartial() {
          eu.hellek.gba.proto.LoginInfoProtos.LoginInfo.UserFavouritePositionProxy result = new eu.hellek.gba.proto.LoginInfoProtos.LoginInfo.UserFavouritePositionProxy(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.lat_ = lat_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.lon_ = lon_;
          if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
            to_bitField0_ |= 0x00000004;
          }
          result.name_ = name_;
          if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
            to_bitField0_ |= 0x00000008;
          }
          result.key_ = key_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }
        
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof eu.hellek.gba.proto.LoginInfoProtos.LoginInfo.UserFavouritePositionProxy) {
            return mergeFrom((eu.hellek.gba.proto.LoginInfoProtos.LoginInfo.UserFavouritePositionProxy)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }
        
        public Builder mergeFrom(eu.hellek.gba.proto.LoginInfoProtos.LoginInfo.UserFavouritePositionProxy other) {
          if (other == eu.hellek.gba.proto.LoginInfoProtos.LoginInfo.UserFavouritePositionProxy.getDefaultInstance()) return this;
          if (other.hasLat()) {
            setLat(other.getLat());
          }
          if (other.hasLon()) {
            setLon(other.getLon());
          }
          if (other.hasName()) {
            setName(other.getName());
          }
          if (other.hasKey()) {
            setKey(other.getKey());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }
        
        public final boolean isInitialized() {
          if (!hasLat()) {
            
            return false;
          }
          if (!hasLon()) {
            
            return false;
          }
          if (!hasName()) {
            
            return false;
          }
          if (!hasKey()) {
            
            return false;
          }
          return true;
        }
        
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder(
              this.getUnknownFields());
          while (true) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  this.setUnknownFields(unknownFields.build());
                  onChanged();
                  return this;
                }
                break;
              }
              case 9: {
                bitField0_ |= 0x00000001;
                lat_ = input.readDouble();
                break;
              }
              case 17: {
                bitField0_ |= 0x00000002;
                lon_ = input.readDouble();
                break;
              }
              case 26: {
                bitField0_ |= 0x00000004;
                name_ = input.readBytes();
                break;
              }
              case 34: {
                bitField0_ |= 0x00000008;
                key_ = input.readBytes();
                break;
              }
            }
          }
        }
        
        private int bitField0_;
        
        // required double lat = 1;
        private double lat_ ;
        public boolean hasLat() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        public double getLat() {
          return lat_;
        }
        public Builder setLat(double value) {
          bitField0_ |= 0x00000001;
          lat_ = value;
          onChanged();
          return this;
        }
        public Builder clearLat() {
          bitField0_ = (bitField0_ & ~0x00000001);
          lat_ = 0D;
          onChanged();
          return this;
        }
        
        // required double lon = 2;
        private double lon_ ;
        public boolean hasLon() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        public double getLon() {
          return lon_;
        }
        public Builder setLon(double value) {
          bitField0_ |= 0x00000002;
          lon_ = value;
          onChanged();
          return this;
        }
        public Builder clearLon() {
          bitField0_ = (bitField0_ & ~0x00000002);
          lon_ = 0D;
          onChanged();
          return this;
        }
        
        // required string name = 3;
        private java.lang.Object name_ = "";
        public boolean hasName() {
          return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        public String getName() {
          java.lang.Object ref = name_;
          if (!(ref instanceof String)) {
            String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
            name_ = s;
            return s;
          } else {
            return (String) ref;
          }
        }
        public Builder setName(String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
          name_ = value;
          onChanged();
          return this;
        }
        public Builder clearName() {
          bitField0_ = (bitField0_ & ~0x00000004);
          name_ = getDefaultInstance().getName();
          onChanged();
          return this;
        }
        void setName(com.google.protobuf.ByteString value) {
          bitField0_ |= 0x00000004;
          name_ = value;
          onChanged();
        }
        
        // required string key = 4;
        private java.lang.Object key_ = "";
        public boolean hasKey() {
          return ((bitField0_ & 0x00000008) == 0x00000008);
        }
        public String getKey() {
          java.lang.Object ref = key_;
          if (!(ref instanceof String)) {
            String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
            key_ = s;
            return s;
          } else {
            return (String) ref;
          }
        }
        public Builder setKey(String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
          key_ = value;
          onChanged();
          return this;
        }
        public Builder clearKey() {
          bitField0_ = (bitField0_ & ~0x00000008);
          key_ = getDefaultInstance().getKey();
          onChanged();
          return this;
        }
        void setKey(com.google.protobuf.ByteString value) {
          bitField0_ |= 0x00000008;
          key_ = value;
          onChanged();
        }
        
        // @@protoc_insertion_point(builder_scope:colectivos.LoginInfo.UserFavouritePositionProxy)
      }
      
      static {
        defaultInstance = new UserFavouritePositionProxy(true);
        defaultInstance.initFields();
      }
      
      // @@protoc_insertion_point(class_scope:colectivos.LoginInfo.UserFavouritePositionProxy)
    }
    
    private int bitField0_;
    // required bool loggedIn = 1;
    public static final int LOGGEDIN_FIELD_NUMBER = 1;
    private boolean loggedIn_;
    public boolean hasLoggedIn() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public boolean getLoggedIn() {
      return loggedIn_;
    }
    
    // optional string loginUrl = 2;
    public static final int LOGINURL_FIELD_NUMBER = 2;
    private java.lang.Object loginUrl_;
    public boolean hasLoginUrl() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getLoginUrl() {
      java.lang.Object ref = loginUrl_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          loginUrl_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getLoginUrlBytes() {
      java.lang.Object ref = loginUrl_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        loginUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string logoutUrl = 3;
    public static final int LOGOUTURL_FIELD_NUMBER = 3;
    private java.lang.Object logoutUrl_;
    public boolean hasLogoutUrl() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getLogoutUrl() {
      java.lang.Object ref = logoutUrl_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          logoutUrl_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getLogoutUrlBytes() {
      java.lang.Object ref = logoutUrl_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        logoutUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string emailAddress = 4;
    public static final int EMAILADDRESS_FIELD_NUMBER = 4;
    private java.lang.Object emailAddress_;
    public boolean hasEmailAddress() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public String getEmailAddress() {
      java.lang.Object ref = emailAddress_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          emailAddress_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getEmailAddressBytes() {
      java.lang.Object ref = emailAddress_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        emailAddress_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string nickname = 5;
    public static final int NICKNAME_FIELD_NUMBER = 5;
    private java.lang.Object nickname_;
    public boolean hasNickname() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public String getNickname() {
      java.lang.Object ref = nickname_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          nickname_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNicknameBytes() {
      java.lang.Object ref = nickname_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        nickname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // repeated .colectivos.LoginInfo.UserFavouritePositionProxy favourites = 6;
    public static final int FAVOURITES_FIELD_NUMBER = 6;
    private java.util.List<eu.hellek.gba.proto.LoginInfoProtos.LoginInfo.UserFavouritePositionProxy> favourites_;
    public java.util.List<eu.hellek.gba.proto.LoginInfoProtos.LoginInfo.UserFavouritePositionProxy> getFavouritesList() {
      return favourites_;
    }
    public java.util.List<? extends eu.hellek.gba.proto.LoginInfoProtos.LoginInfo.UserFavouritePositionProxyOrBuilder> 
        getFavouritesOrBuilderList() {
      return favourites_;
    }
    public int getFavouritesCount() {
      return favourites_.size();
    }
    public eu.hellek.gba.proto.LoginInfoProtos.LoginInfo.UserFavouritePositionProxy getFavourites(int index) {
      return favourites_.get(index);
    }
    public eu.hellek.gba.proto.LoginInfoProtos.LoginInfo.UserFavouritePositionProxyOrBuilder getFavouritesOrBuilder(
        int index) {
      return favourites_.get(index);
    }
    
    private void initFields() {
      loggedIn_ = false;
      loginUrl_ = "";
      logoutUrl_ = "";
      emailAddress_ = "";
      nickname_ = "";
      favourites_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasLoggedIn()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getFavouritesCount(); i++) {
        if (!getFavourites(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBool(1, loggedIn_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getLoginUrlBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getLogoutUrlBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getEmailAddressBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getNicknameBytes());
      }
      for (int i = 0; i < favourites_.size(); i++) {
        output.writeMessage(6, favourites_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, loggedIn_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getLoginUrlBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getLogoutUrlBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getEmailAddressBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getNicknameBytes());
      }
      for (int i = 0; i < favourites_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, favourites_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static eu.hellek.gba.proto.LoginInfoProtos.LoginInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static eu.hellek.gba.proto.LoginInfoProtos.LoginInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static eu.hellek.gba.proto.LoginInfoProtos.LoginInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static eu.hellek.gba.proto.LoginInfoProtos.LoginInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static eu.hellek.gba.proto.LoginInfoProtos.LoginInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static eu.hellek.gba.proto.LoginInfoProtos.LoginInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static eu.hellek.gba.proto.LoginInfoProtos.LoginInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static eu.hellek.gba.proto.LoginInfoProtos.LoginInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static eu.hellek.gba.proto.LoginInfoProtos.LoginInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static eu.hellek.gba.proto.LoginInfoProtos.LoginInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(eu.hellek.gba.proto.LoginInfoProtos.LoginInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements eu.hellek.gba.proto.LoginInfoProtos.LoginInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return eu.hellek.gba.proto.LoginInfoProtos.internal_static_colectivos_LoginInfo_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return eu.hellek.gba.proto.LoginInfoProtos.internal_static_colectivos_LoginInfo_fieldAccessorTable;
      }
      
      // Construct using eu.hellek.gba.proto.LoginInfoProtos.LoginInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getFavouritesFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        loggedIn_ = false;
        bitField0_ = (bitField0_ & ~0x00000001);
        loginUrl_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        logoutUrl_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        emailAddress_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        nickname_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        if (favouritesBuilder_ == null) {
          favourites_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000020);
        } else {
          favouritesBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return eu.hellek.gba.proto.LoginInfoProtos.LoginInfo.getDescriptor();
      }
      
      public eu.hellek.gba.proto.LoginInfoProtos.LoginInfo getDefaultInstanceForType() {
        return eu.hellek.gba.proto.LoginInfoProtos.LoginInfo.getDefaultInstance();
      }
      
      public eu.hellek.gba.proto.LoginInfoProtos.LoginInfo build() {
        eu.hellek.gba.proto.LoginInfoProtos.LoginInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private eu.hellek.gba.proto.LoginInfoProtos.LoginInfo buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        eu.hellek.gba.proto.LoginInfoProtos.LoginInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public eu.hellek.gba.proto.LoginInfoProtos.LoginInfo buildPartial() {
        eu.hellek.gba.proto.LoginInfoProtos.LoginInfo result = new eu.hellek.gba.proto.LoginInfoProtos.LoginInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.loggedIn_ = loggedIn_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.loginUrl_ = loginUrl_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.logoutUrl_ = logoutUrl_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.emailAddress_ = emailAddress_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.nickname_ = nickname_;
        if (favouritesBuilder_ == null) {
          if (((bitField0_ & 0x00000020) == 0x00000020)) {
            favourites_ = java.util.Collections.unmodifiableList(favourites_);
            bitField0_ = (bitField0_ & ~0x00000020);
          }
          result.favourites_ = favourites_;
        } else {
          result.favourites_ = favouritesBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof eu.hellek.gba.proto.LoginInfoProtos.LoginInfo) {
          return mergeFrom((eu.hellek.gba.proto.LoginInfoProtos.LoginInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(eu.hellek.gba.proto.LoginInfoProtos.LoginInfo other) {
        if (other == eu.hellek.gba.proto.LoginInfoProtos.LoginInfo.getDefaultInstance()) return this;
        if (other.hasLoggedIn()) {
          setLoggedIn(other.getLoggedIn());
        }
        if (other.hasLoginUrl()) {
          setLoginUrl(other.getLoginUrl());
        }
        if (other.hasLogoutUrl()) {
          setLogoutUrl(other.getLogoutUrl());
        }
        if (other.hasEmailAddress()) {
          setEmailAddress(other.getEmailAddress());
        }
        if (other.hasNickname()) {
          setNickname(other.getNickname());
        }
        if (favouritesBuilder_ == null) {
          if (!other.favourites_.isEmpty()) {
            if (favourites_.isEmpty()) {
              favourites_ = other.favourites_;
              bitField0_ = (bitField0_ & ~0x00000020);
            } else {
              ensureFavouritesIsMutable();
              favourites_.addAll(other.favourites_);
            }
            onChanged();
          }
        } else {
          if (!other.favourites_.isEmpty()) {
            if (favouritesBuilder_.isEmpty()) {
              favouritesBuilder_.dispose();
              favouritesBuilder_ = null;
              favourites_ = other.favourites_;
              bitField0_ = (bitField0_ & ~0x00000020);
              favouritesBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getFavouritesFieldBuilder() : null;
            } else {
              favouritesBuilder_.addAllMessages(other.favourites_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasLoggedIn()) {
          
          return false;
        }
        for (int i = 0; i < getFavouritesCount(); i++) {
          if (!getFavourites(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              loggedIn_ = input.readBool();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              loginUrl_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              logoutUrl_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              emailAddress_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              nickname_ = input.readBytes();
              break;
            }
            case 50: {
              eu.hellek.gba.proto.LoginInfoProtos.LoginInfo.UserFavouritePositionProxy.Builder subBuilder = eu.hellek.gba.proto.LoginInfoProtos.LoginInfo.UserFavouritePositionProxy.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addFavourites(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required bool loggedIn = 1;
      private boolean loggedIn_ ;
      public boolean hasLoggedIn() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public boolean getLoggedIn() {
        return loggedIn_;
      }
      public Builder setLoggedIn(boolean value) {
        bitField0_ |= 0x00000001;
        loggedIn_ = value;
        onChanged();
        return this;
      }
      public Builder clearLoggedIn() {
        bitField0_ = (bitField0_ & ~0x00000001);
        loggedIn_ = false;
        onChanged();
        return this;
      }
      
      // optional string loginUrl = 2;
      private java.lang.Object loginUrl_ = "";
      public boolean hasLoginUrl() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getLoginUrl() {
        java.lang.Object ref = loginUrl_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          loginUrl_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setLoginUrl(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        loginUrl_ = value;
        onChanged();
        return this;
      }
      public Builder clearLoginUrl() {
        bitField0_ = (bitField0_ & ~0x00000002);
        loginUrl_ = getDefaultInstance().getLoginUrl();
        onChanged();
        return this;
      }
      void setLoginUrl(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        loginUrl_ = value;
        onChanged();
      }
      
      // optional string logoutUrl = 3;
      private java.lang.Object logoutUrl_ = "";
      public boolean hasLogoutUrl() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getLogoutUrl() {
        java.lang.Object ref = logoutUrl_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          logoutUrl_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setLogoutUrl(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        logoutUrl_ = value;
        onChanged();
        return this;
      }
      public Builder clearLogoutUrl() {
        bitField0_ = (bitField0_ & ~0x00000004);
        logoutUrl_ = getDefaultInstance().getLogoutUrl();
        onChanged();
        return this;
      }
      void setLogoutUrl(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        logoutUrl_ = value;
        onChanged();
      }
      
      // optional string emailAddress = 4;
      private java.lang.Object emailAddress_ = "";
      public boolean hasEmailAddress() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public String getEmailAddress() {
        java.lang.Object ref = emailAddress_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          emailAddress_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setEmailAddress(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        emailAddress_ = value;
        onChanged();
        return this;
      }
      public Builder clearEmailAddress() {
        bitField0_ = (bitField0_ & ~0x00000008);
        emailAddress_ = getDefaultInstance().getEmailAddress();
        onChanged();
        return this;
      }
      void setEmailAddress(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000008;
        emailAddress_ = value;
        onChanged();
      }
      
      // optional string nickname = 5;
      private java.lang.Object nickname_ = "";
      public boolean hasNickname() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public String getNickname() {
        java.lang.Object ref = nickname_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          nickname_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setNickname(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        nickname_ = value;
        onChanged();
        return this;
      }
      public Builder clearNickname() {
        bitField0_ = (bitField0_ & ~0x00000010);
        nickname_ = getDefaultInstance().getNickname();
        onChanged();
        return this;
      }
      void setNickname(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000010;
        nickname_ = value;
        onChanged();
      }
      
      // repeated .colectivos.LoginInfo.UserFavouritePositionProxy favourites = 6;
      private java.util.List<eu.hellek.gba.proto.LoginInfoProtos.LoginInfo.UserFavouritePositionProxy> favourites_ =
        java.util.Collections.emptyList();
      private void ensureFavouritesIsMutable() {
        if (!((bitField0_ & 0x00000020) == 0x00000020)) {
          favourites_ = new java.util.ArrayList<eu.hellek.gba.proto.LoginInfoProtos.LoginInfo.UserFavouritePositionProxy>(favourites_);
          bitField0_ |= 0x00000020;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          eu.hellek.gba.proto.LoginInfoProtos.LoginInfo.UserFavouritePositionProxy, eu.hellek.gba.proto.LoginInfoProtos.LoginInfo.UserFavouritePositionProxy.Builder, eu.hellek.gba.proto.LoginInfoProtos.LoginInfo.UserFavouritePositionProxyOrBuilder> favouritesBuilder_;
      
      public java.util.List<eu.hellek.gba.proto.LoginInfoProtos.LoginInfo.UserFavouritePositionProxy> getFavouritesList() {
        if (favouritesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(favourites_);
        } else {
          return favouritesBuilder_.getMessageList();
        }
      }
      public int getFavouritesCount() {
        if (favouritesBuilder_ == null) {
          return favourites_.size();
        } else {
          return favouritesBuilder_.getCount();
        }
      }
      public eu.hellek.gba.proto.LoginInfoProtos.LoginInfo.UserFavouritePositionProxy getFavourites(int index) {
        if (favouritesBuilder_ == null) {
          return favourites_.get(index);
        } else {
          return favouritesBuilder_.getMessage(index);
        }
      }
      public Builder setFavourites(
          int index, eu.hellek.gba.proto.LoginInfoProtos.LoginInfo.UserFavouritePositionProxy value) {
        if (favouritesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFavouritesIsMutable();
          favourites_.set(index, value);
          onChanged();
        } else {
          favouritesBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setFavourites(
          int index, eu.hellek.gba.proto.LoginInfoProtos.LoginInfo.UserFavouritePositionProxy.Builder builderForValue) {
        if (favouritesBuilder_ == null) {
          ensureFavouritesIsMutable();
          favourites_.set(index, builderForValue.build());
          onChanged();
        } else {
          favouritesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addFavourites(eu.hellek.gba.proto.LoginInfoProtos.LoginInfo.UserFavouritePositionProxy value) {
        if (favouritesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFavouritesIsMutable();
          favourites_.add(value);
          onChanged();
        } else {
          favouritesBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addFavourites(
          int index, eu.hellek.gba.proto.LoginInfoProtos.LoginInfo.UserFavouritePositionProxy value) {
        if (favouritesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFavouritesIsMutable();
          favourites_.add(index, value);
          onChanged();
        } else {
          favouritesBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addFavourites(
          eu.hellek.gba.proto.LoginInfoProtos.LoginInfo.UserFavouritePositionProxy.Builder builderForValue) {
        if (favouritesBuilder_ == null) {
          ensureFavouritesIsMutable();
          favourites_.add(builderForValue.build());
          onChanged();
        } else {
          favouritesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addFavourites(
          int index, eu.hellek.gba.proto.LoginInfoProtos.LoginInfo.UserFavouritePositionProxy.Builder builderForValue) {
        if (favouritesBuilder_ == null) {
          ensureFavouritesIsMutable();
          favourites_.add(index, builderForValue.build());
          onChanged();
        } else {
          favouritesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllFavourites(
          java.lang.Iterable<? extends eu.hellek.gba.proto.LoginInfoProtos.LoginInfo.UserFavouritePositionProxy> values) {
        if (favouritesBuilder_ == null) {
          ensureFavouritesIsMutable();
          super.addAll(values, favourites_);
          onChanged();
        } else {
          favouritesBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearFavourites() {
        if (favouritesBuilder_ == null) {
          favourites_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000020);
          onChanged();
        } else {
          favouritesBuilder_.clear();
        }
        return this;
      }
      public Builder removeFavourites(int index) {
        if (favouritesBuilder_ == null) {
          ensureFavouritesIsMutable();
          favourites_.remove(index);
          onChanged();
        } else {
          favouritesBuilder_.remove(index);
        }
        return this;
      }
      public eu.hellek.gba.proto.LoginInfoProtos.LoginInfo.UserFavouritePositionProxy.Builder getFavouritesBuilder(
          int index) {
        return getFavouritesFieldBuilder().getBuilder(index);
      }
      public eu.hellek.gba.proto.LoginInfoProtos.LoginInfo.UserFavouritePositionProxyOrBuilder getFavouritesOrBuilder(
          int index) {
        if (favouritesBuilder_ == null) {
          return favourites_.get(index);  } else {
          return favouritesBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends eu.hellek.gba.proto.LoginInfoProtos.LoginInfo.UserFavouritePositionProxyOrBuilder> 
           getFavouritesOrBuilderList() {
        if (favouritesBuilder_ != null) {
          return favouritesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(favourites_);
        }
      }
      public eu.hellek.gba.proto.LoginInfoProtos.LoginInfo.UserFavouritePositionProxy.Builder addFavouritesBuilder() {
        return getFavouritesFieldBuilder().addBuilder(
            eu.hellek.gba.proto.LoginInfoProtos.LoginInfo.UserFavouritePositionProxy.getDefaultInstance());
      }
      public eu.hellek.gba.proto.LoginInfoProtos.LoginInfo.UserFavouritePositionProxy.Builder addFavouritesBuilder(
          int index) {
        return getFavouritesFieldBuilder().addBuilder(
            index, eu.hellek.gba.proto.LoginInfoProtos.LoginInfo.UserFavouritePositionProxy.getDefaultInstance());
      }
      public java.util.List<eu.hellek.gba.proto.LoginInfoProtos.LoginInfo.UserFavouritePositionProxy.Builder> 
           getFavouritesBuilderList() {
        return getFavouritesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          eu.hellek.gba.proto.LoginInfoProtos.LoginInfo.UserFavouritePositionProxy, eu.hellek.gba.proto.LoginInfoProtos.LoginInfo.UserFavouritePositionProxy.Builder, eu.hellek.gba.proto.LoginInfoProtos.LoginInfo.UserFavouritePositionProxyOrBuilder> 
          getFavouritesFieldBuilder() {
        if (favouritesBuilder_ == null) {
          favouritesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              eu.hellek.gba.proto.LoginInfoProtos.LoginInfo.UserFavouritePositionProxy, eu.hellek.gba.proto.LoginInfoProtos.LoginInfo.UserFavouritePositionProxy.Builder, eu.hellek.gba.proto.LoginInfoProtos.LoginInfo.UserFavouritePositionProxyOrBuilder>(
                  favourites_,
                  ((bitField0_ & 0x00000020) == 0x00000020),
                  getParentForChildren(),
                  isClean());
          favourites_ = null;
        }
        return favouritesBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:colectivos.LoginInfo)
    }
    
    static {
      defaultInstance = new LoginInfo(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:colectivos.LoginInfo)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_colectivos_LoginInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_colectivos_LoginInfo_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_colectivos_LoginInfo_UserFavouritePositionProxy_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_colectivos_LoginInfo_UserFavouritePositionProxy_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017LoginInfo.proto\022\ncolectivos\"\203\002\n\tLoginI" +
      "nfo\022\020\n\010loggedIn\030\001 \002(\010\022\020\n\010loginUrl\030\002 \001(\t\022" +
      "\021\n\tlogoutUrl\030\003 \001(\t\022\024\n\014emailAddress\030\004 \001(\t" +
      "\022\020\n\010nickname\030\005 \001(\t\022D\n\nfavourites\030\006 \003(\01320" +
      ".colectivos.LoginInfo.UserFavouritePosit" +
      "ionProxy\032Q\n\032UserFavouritePositionProxy\022\013" +
      "\n\003lat\030\001 \002(\001\022\013\n\003lon\030\002 \002(\001\022\014\n\004name\030\003 \002(\t\022\013" +
      "\n\003key\030\004 \002(\tB&\n\023eu.hellek.gba.protoB\017Logi" +
      "nInfoProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_colectivos_LoginInfo_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_colectivos_LoginInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_colectivos_LoginInfo_descriptor,
              new java.lang.String[] { "LoggedIn", "LoginUrl", "LogoutUrl", "EmailAddress", "Nickname", "Favourites", },
              eu.hellek.gba.proto.LoginInfoProtos.LoginInfo.class,
              eu.hellek.gba.proto.LoginInfoProtos.LoginInfo.Builder.class);
          internal_static_colectivos_LoginInfo_UserFavouritePositionProxy_descriptor =
            internal_static_colectivos_LoginInfo_descriptor.getNestedTypes().get(0);
          internal_static_colectivos_LoginInfo_UserFavouritePositionProxy_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_colectivos_LoginInfo_UserFavouritePositionProxy_descriptor,
              new java.lang.String[] { "Lat", "Lon", "Name", "Key", },
              eu.hellek.gba.proto.LoginInfoProtos.LoginInfo.UserFavouritePositionProxy.class,
              eu.hellek.gba.proto.LoginInfoProtos.LoginInfo.UserFavouritePositionProxy.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
