// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Requests.proto

package eu.hellek.gba.proto;

public final class RequestsProtos {
  private RequestsProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface DirectSearchRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required float lat1 = 1;
    boolean hasLat1();
    float getLat1();
    
    // required float lon1 = 2;
    boolean hasLon1();
    float getLon1();
    
    // required float lat2 = 3;
    boolean hasLat2();
    float getLat2();
    
    // required float lon2 = 4;
    boolean hasLon2();
    float getLon2();
    
    // required bool ignoreTrains = 5;
    boolean hasIgnoreTrains();
    boolean getIgnoreTrains();
    
    // required bool ignoreSubte = 6;
    boolean hasIgnoreSubte();
    boolean getIgnoreSubte();
  }
  public static final class DirectSearchRequest extends
      com.google.protobuf.GeneratedMessage
      implements DirectSearchRequestOrBuilder {
    // Use DirectSearchRequest.newBuilder() to construct.
    private DirectSearchRequest(Builder builder) {
      super(builder);
    }
    private DirectSearchRequest(boolean noInit) {}
    
    private static final DirectSearchRequest defaultInstance;
    public static DirectSearchRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public DirectSearchRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return eu.hellek.gba.proto.RequestsProtos.internal_static_colectivos_DirectSearchRequest_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return eu.hellek.gba.proto.RequestsProtos.internal_static_colectivos_DirectSearchRequest_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required float lat1 = 1;
    public static final int LAT1_FIELD_NUMBER = 1;
    private float lat1_;
    public boolean hasLat1() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public float getLat1() {
      return lat1_;
    }
    
    // required float lon1 = 2;
    public static final int LON1_FIELD_NUMBER = 2;
    private float lon1_;
    public boolean hasLon1() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public float getLon1() {
      return lon1_;
    }
    
    // required float lat2 = 3;
    public static final int LAT2_FIELD_NUMBER = 3;
    private float lat2_;
    public boolean hasLat2() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public float getLat2() {
      return lat2_;
    }
    
    // required float lon2 = 4;
    public static final int LON2_FIELD_NUMBER = 4;
    private float lon2_;
    public boolean hasLon2() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public float getLon2() {
      return lon2_;
    }
    
    // required bool ignoreTrains = 5;
    public static final int IGNORETRAINS_FIELD_NUMBER = 5;
    private boolean ignoreTrains_;
    public boolean hasIgnoreTrains() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public boolean getIgnoreTrains() {
      return ignoreTrains_;
    }
    
    // required bool ignoreSubte = 6;
    public static final int IGNORESUBTE_FIELD_NUMBER = 6;
    private boolean ignoreSubte_;
    public boolean hasIgnoreSubte() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public boolean getIgnoreSubte() {
      return ignoreSubte_;
    }
    
    private void initFields() {
      lat1_ = 0F;
      lon1_ = 0F;
      lat2_ = 0F;
      lon2_ = 0F;
      ignoreTrains_ = false;
      ignoreSubte_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasLat1()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLon1()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLat2()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLon2()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasIgnoreTrains()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasIgnoreSubte()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeFloat(1, lat1_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeFloat(2, lon1_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeFloat(3, lat2_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeFloat(4, lon2_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBool(5, ignoreTrains_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBool(6, ignoreSubte_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(1, lat1_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, lon1_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, lat2_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(4, lon2_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, ignoreTrains_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(6, ignoreSubte_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static eu.hellek.gba.proto.RequestsProtos.DirectSearchRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static eu.hellek.gba.proto.RequestsProtos.DirectSearchRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static eu.hellek.gba.proto.RequestsProtos.DirectSearchRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static eu.hellek.gba.proto.RequestsProtos.DirectSearchRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static eu.hellek.gba.proto.RequestsProtos.DirectSearchRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static eu.hellek.gba.proto.RequestsProtos.DirectSearchRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static eu.hellek.gba.proto.RequestsProtos.DirectSearchRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static eu.hellek.gba.proto.RequestsProtos.DirectSearchRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static eu.hellek.gba.proto.RequestsProtos.DirectSearchRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static eu.hellek.gba.proto.RequestsProtos.DirectSearchRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(eu.hellek.gba.proto.RequestsProtos.DirectSearchRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements eu.hellek.gba.proto.RequestsProtos.DirectSearchRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return eu.hellek.gba.proto.RequestsProtos.internal_static_colectivos_DirectSearchRequest_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return eu.hellek.gba.proto.RequestsProtos.internal_static_colectivos_DirectSearchRequest_fieldAccessorTable;
      }
      
      // Construct using eu.hellek.gba.proto.RequestsProtos.DirectSearchRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        lat1_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000001);
        lon1_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000002);
        lat2_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000004);
        lon2_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000008);
        ignoreTrains_ = false;
        bitField0_ = (bitField0_ & ~0x00000010);
        ignoreSubte_ = false;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return eu.hellek.gba.proto.RequestsProtos.DirectSearchRequest.getDescriptor();
      }
      
      public eu.hellek.gba.proto.RequestsProtos.DirectSearchRequest getDefaultInstanceForType() {
        return eu.hellek.gba.proto.RequestsProtos.DirectSearchRequest.getDefaultInstance();
      }
      
      public eu.hellek.gba.proto.RequestsProtos.DirectSearchRequest build() {
        eu.hellek.gba.proto.RequestsProtos.DirectSearchRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private eu.hellek.gba.proto.RequestsProtos.DirectSearchRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        eu.hellek.gba.proto.RequestsProtos.DirectSearchRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public eu.hellek.gba.proto.RequestsProtos.DirectSearchRequest buildPartial() {
        eu.hellek.gba.proto.RequestsProtos.DirectSearchRequest result = new eu.hellek.gba.proto.RequestsProtos.DirectSearchRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.lat1_ = lat1_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.lon1_ = lon1_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.lat2_ = lat2_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.lon2_ = lon2_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.ignoreTrains_ = ignoreTrains_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.ignoreSubte_ = ignoreSubte_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof eu.hellek.gba.proto.RequestsProtos.DirectSearchRequest) {
          return mergeFrom((eu.hellek.gba.proto.RequestsProtos.DirectSearchRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(eu.hellek.gba.proto.RequestsProtos.DirectSearchRequest other) {
        if (other == eu.hellek.gba.proto.RequestsProtos.DirectSearchRequest.getDefaultInstance()) return this;
        if (other.hasLat1()) {
          setLat1(other.getLat1());
        }
        if (other.hasLon1()) {
          setLon1(other.getLon1());
        }
        if (other.hasLat2()) {
          setLat2(other.getLat2());
        }
        if (other.hasLon2()) {
          setLon2(other.getLon2());
        }
        if (other.hasIgnoreTrains()) {
          setIgnoreTrains(other.getIgnoreTrains());
        }
        if (other.hasIgnoreSubte()) {
          setIgnoreSubte(other.getIgnoreSubte());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasLat1()) {
          
          return false;
        }
        if (!hasLon1()) {
          
          return false;
        }
        if (!hasLat2()) {
          
          return false;
        }
        if (!hasLon2()) {
          
          return false;
        }
        if (!hasIgnoreTrains()) {
          
          return false;
        }
        if (!hasIgnoreSubte()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 13: {
              bitField0_ |= 0x00000001;
              lat1_ = input.readFloat();
              break;
            }
            case 21: {
              bitField0_ |= 0x00000002;
              lon1_ = input.readFloat();
              break;
            }
            case 29: {
              bitField0_ |= 0x00000004;
              lat2_ = input.readFloat();
              break;
            }
            case 37: {
              bitField0_ |= 0x00000008;
              lon2_ = input.readFloat();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              ignoreTrains_ = input.readBool();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              ignoreSubte_ = input.readBool();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required float lat1 = 1;
      private float lat1_ ;
      public boolean hasLat1() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public float getLat1() {
        return lat1_;
      }
      public Builder setLat1(float value) {
        bitField0_ |= 0x00000001;
        lat1_ = value;
        onChanged();
        return this;
      }
      public Builder clearLat1() {
        bitField0_ = (bitField0_ & ~0x00000001);
        lat1_ = 0F;
        onChanged();
        return this;
      }
      
      // required float lon1 = 2;
      private float lon1_ ;
      public boolean hasLon1() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public float getLon1() {
        return lon1_;
      }
      public Builder setLon1(float value) {
        bitField0_ |= 0x00000002;
        lon1_ = value;
        onChanged();
        return this;
      }
      public Builder clearLon1() {
        bitField0_ = (bitField0_ & ~0x00000002);
        lon1_ = 0F;
        onChanged();
        return this;
      }
      
      // required float lat2 = 3;
      private float lat2_ ;
      public boolean hasLat2() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public float getLat2() {
        return lat2_;
      }
      public Builder setLat2(float value) {
        bitField0_ |= 0x00000004;
        lat2_ = value;
        onChanged();
        return this;
      }
      public Builder clearLat2() {
        bitField0_ = (bitField0_ & ~0x00000004);
        lat2_ = 0F;
        onChanged();
        return this;
      }
      
      // required float lon2 = 4;
      private float lon2_ ;
      public boolean hasLon2() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public float getLon2() {
        return lon2_;
      }
      public Builder setLon2(float value) {
        bitField0_ |= 0x00000008;
        lon2_ = value;
        onChanged();
        return this;
      }
      public Builder clearLon2() {
        bitField0_ = (bitField0_ & ~0x00000008);
        lon2_ = 0F;
        onChanged();
        return this;
      }
      
      // required bool ignoreTrains = 5;
      private boolean ignoreTrains_ ;
      public boolean hasIgnoreTrains() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public boolean getIgnoreTrains() {
        return ignoreTrains_;
      }
      public Builder setIgnoreTrains(boolean value) {
        bitField0_ |= 0x00000010;
        ignoreTrains_ = value;
        onChanged();
        return this;
      }
      public Builder clearIgnoreTrains() {
        bitField0_ = (bitField0_ & ~0x00000010);
        ignoreTrains_ = false;
        onChanged();
        return this;
      }
      
      // required bool ignoreSubte = 6;
      private boolean ignoreSubte_ ;
      public boolean hasIgnoreSubte() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public boolean getIgnoreSubte() {
        return ignoreSubte_;
      }
      public Builder setIgnoreSubte(boolean value) {
        bitField0_ |= 0x00000020;
        ignoreSubte_ = value;
        onChanged();
        return this;
      }
      public Builder clearIgnoreSubte() {
        bitField0_ = (bitField0_ & ~0x00000020);
        ignoreSubte_ = false;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:colectivos.DirectSearchRequest)
    }
    
    static {
      defaultInstance = new DirectSearchRequest(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:colectivos.DirectSearchRequest)
  }
  
  public interface IndirectSearchRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required float lat1 = 1;
    boolean hasLat1();
    float getLat1();
    
    // required float lon1 = 2;
    boolean hasLon1();
    float getLon1();
    
    // required float lat2 = 3;
    boolean hasLat2();
    float getLat2();
    
    // required float lon2 = 4;
    boolean hasLon2();
    float getLon2();
    
    // required bool ignoreTrains = 5;
    boolean hasIgnoreTrains();
    boolean getIgnoreTrains();
    
    // required bool ignoreSubte = 6;
    boolean hasIgnoreSubte();
    boolean getIgnoreSubte();
    
    // repeated string mlkSet1String = 7;
    java.util.List<String> getMlkSet1StringList();
    int getMlkSet1StringCount();
    String getMlkSet1String(int index);
    
    // repeated string mlkSet2String = 8;
    java.util.List<String> getMlkSet2StringList();
    int getMlkSet2StringCount();
    String getMlkSet2String(int index);
  }
  public static final class IndirectSearchRequest extends
      com.google.protobuf.GeneratedMessage
      implements IndirectSearchRequestOrBuilder {
    // Use IndirectSearchRequest.newBuilder() to construct.
    private IndirectSearchRequest(Builder builder) {
      super(builder);
    }
    private IndirectSearchRequest(boolean noInit) {}
    
    private static final IndirectSearchRequest defaultInstance;
    public static IndirectSearchRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public IndirectSearchRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return eu.hellek.gba.proto.RequestsProtos.internal_static_colectivos_IndirectSearchRequest_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return eu.hellek.gba.proto.RequestsProtos.internal_static_colectivos_IndirectSearchRequest_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required float lat1 = 1;
    public static final int LAT1_FIELD_NUMBER = 1;
    private float lat1_;
    public boolean hasLat1() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public float getLat1() {
      return lat1_;
    }
    
    // required float lon1 = 2;
    public static final int LON1_FIELD_NUMBER = 2;
    private float lon1_;
    public boolean hasLon1() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public float getLon1() {
      return lon1_;
    }
    
    // required float lat2 = 3;
    public static final int LAT2_FIELD_NUMBER = 3;
    private float lat2_;
    public boolean hasLat2() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public float getLat2() {
      return lat2_;
    }
    
    // required float lon2 = 4;
    public static final int LON2_FIELD_NUMBER = 4;
    private float lon2_;
    public boolean hasLon2() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public float getLon2() {
      return lon2_;
    }
    
    // required bool ignoreTrains = 5;
    public static final int IGNORETRAINS_FIELD_NUMBER = 5;
    private boolean ignoreTrains_;
    public boolean hasIgnoreTrains() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public boolean getIgnoreTrains() {
      return ignoreTrains_;
    }
    
    // required bool ignoreSubte = 6;
    public static final int IGNORESUBTE_FIELD_NUMBER = 6;
    private boolean ignoreSubte_;
    public boolean hasIgnoreSubte() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public boolean getIgnoreSubte() {
      return ignoreSubte_;
    }
    
    // repeated string mlkSet1String = 7;
    public static final int MLKSET1STRING_FIELD_NUMBER = 7;
    private com.google.protobuf.LazyStringList mlkSet1String_;
    public java.util.List<String>
        getMlkSet1StringList() {
      return mlkSet1String_;
    }
    public int getMlkSet1StringCount() {
      return mlkSet1String_.size();
    }
    public String getMlkSet1String(int index) {
      return mlkSet1String_.get(index);
    }
    
    // repeated string mlkSet2String = 8;
    public static final int MLKSET2STRING_FIELD_NUMBER = 8;
    private com.google.protobuf.LazyStringList mlkSet2String_;
    public java.util.List<String>
        getMlkSet2StringList() {
      return mlkSet2String_;
    }
    public int getMlkSet2StringCount() {
      return mlkSet2String_.size();
    }
    public String getMlkSet2String(int index) {
      return mlkSet2String_.get(index);
    }
    
    private void initFields() {
      lat1_ = 0F;
      lon1_ = 0F;
      lat2_ = 0F;
      lon2_ = 0F;
      ignoreTrains_ = false;
      ignoreSubte_ = false;
      mlkSet1String_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      mlkSet2String_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasLat1()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLon1()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLat2()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLon2()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasIgnoreTrains()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasIgnoreSubte()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeFloat(1, lat1_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeFloat(2, lon1_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeFloat(3, lat2_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeFloat(4, lon2_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBool(5, ignoreTrains_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBool(6, ignoreSubte_);
      }
      for (int i = 0; i < mlkSet1String_.size(); i++) {
        output.writeBytes(7, mlkSet1String_.getByteString(i));
      }
      for (int i = 0; i < mlkSet2String_.size(); i++) {
        output.writeBytes(8, mlkSet2String_.getByteString(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(1, lat1_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, lon1_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, lat2_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(4, lon2_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, ignoreTrains_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(6, ignoreSubte_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < mlkSet1String_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(mlkSet1String_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getMlkSet1StringList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < mlkSet2String_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(mlkSet2String_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getMlkSet2StringList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static eu.hellek.gba.proto.RequestsProtos.IndirectSearchRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static eu.hellek.gba.proto.RequestsProtos.IndirectSearchRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static eu.hellek.gba.proto.RequestsProtos.IndirectSearchRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static eu.hellek.gba.proto.RequestsProtos.IndirectSearchRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static eu.hellek.gba.proto.RequestsProtos.IndirectSearchRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static eu.hellek.gba.proto.RequestsProtos.IndirectSearchRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static eu.hellek.gba.proto.RequestsProtos.IndirectSearchRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static eu.hellek.gba.proto.RequestsProtos.IndirectSearchRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static eu.hellek.gba.proto.RequestsProtos.IndirectSearchRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static eu.hellek.gba.proto.RequestsProtos.IndirectSearchRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(eu.hellek.gba.proto.RequestsProtos.IndirectSearchRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements eu.hellek.gba.proto.RequestsProtos.IndirectSearchRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return eu.hellek.gba.proto.RequestsProtos.internal_static_colectivos_IndirectSearchRequest_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return eu.hellek.gba.proto.RequestsProtos.internal_static_colectivos_IndirectSearchRequest_fieldAccessorTable;
      }
      
      // Construct using eu.hellek.gba.proto.RequestsProtos.IndirectSearchRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        lat1_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000001);
        lon1_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000002);
        lat2_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000004);
        lon2_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000008);
        ignoreTrains_ = false;
        bitField0_ = (bitField0_ & ~0x00000010);
        ignoreSubte_ = false;
        bitField0_ = (bitField0_ & ~0x00000020);
        mlkSet1String_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000040);
        mlkSet2String_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return eu.hellek.gba.proto.RequestsProtos.IndirectSearchRequest.getDescriptor();
      }
      
      public eu.hellek.gba.proto.RequestsProtos.IndirectSearchRequest getDefaultInstanceForType() {
        return eu.hellek.gba.proto.RequestsProtos.IndirectSearchRequest.getDefaultInstance();
      }
      
      public eu.hellek.gba.proto.RequestsProtos.IndirectSearchRequest build() {
        eu.hellek.gba.proto.RequestsProtos.IndirectSearchRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private eu.hellek.gba.proto.RequestsProtos.IndirectSearchRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        eu.hellek.gba.proto.RequestsProtos.IndirectSearchRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public eu.hellek.gba.proto.RequestsProtos.IndirectSearchRequest buildPartial() {
        eu.hellek.gba.proto.RequestsProtos.IndirectSearchRequest result = new eu.hellek.gba.proto.RequestsProtos.IndirectSearchRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.lat1_ = lat1_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.lon1_ = lon1_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.lat2_ = lat2_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.lon2_ = lon2_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.ignoreTrains_ = ignoreTrains_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.ignoreSubte_ = ignoreSubte_;
        if (((bitField0_ & 0x00000040) == 0x00000040)) {
          mlkSet1String_ = new com.google.protobuf.UnmodifiableLazyStringList(
              mlkSet1String_);
          bitField0_ = (bitField0_ & ~0x00000040);
        }
        result.mlkSet1String_ = mlkSet1String_;
        if (((bitField0_ & 0x00000080) == 0x00000080)) {
          mlkSet2String_ = new com.google.protobuf.UnmodifiableLazyStringList(
              mlkSet2String_);
          bitField0_ = (bitField0_ & ~0x00000080);
        }
        result.mlkSet2String_ = mlkSet2String_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof eu.hellek.gba.proto.RequestsProtos.IndirectSearchRequest) {
          return mergeFrom((eu.hellek.gba.proto.RequestsProtos.IndirectSearchRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(eu.hellek.gba.proto.RequestsProtos.IndirectSearchRequest other) {
        if (other == eu.hellek.gba.proto.RequestsProtos.IndirectSearchRequest.getDefaultInstance()) return this;
        if (other.hasLat1()) {
          setLat1(other.getLat1());
        }
        if (other.hasLon1()) {
          setLon1(other.getLon1());
        }
        if (other.hasLat2()) {
          setLat2(other.getLat2());
        }
        if (other.hasLon2()) {
          setLon2(other.getLon2());
        }
        if (other.hasIgnoreTrains()) {
          setIgnoreTrains(other.getIgnoreTrains());
        }
        if (other.hasIgnoreSubte()) {
          setIgnoreSubte(other.getIgnoreSubte());
        }
        if (!other.mlkSet1String_.isEmpty()) {
          if (mlkSet1String_.isEmpty()) {
            mlkSet1String_ = other.mlkSet1String_;
            bitField0_ = (bitField0_ & ~0x00000040);
          } else {
            ensureMlkSet1StringIsMutable();
            mlkSet1String_.addAll(other.mlkSet1String_);
          }
          onChanged();
        }
        if (!other.mlkSet2String_.isEmpty()) {
          if (mlkSet2String_.isEmpty()) {
            mlkSet2String_ = other.mlkSet2String_;
            bitField0_ = (bitField0_ & ~0x00000080);
          } else {
            ensureMlkSet2StringIsMutable();
            mlkSet2String_.addAll(other.mlkSet2String_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasLat1()) {
          
          return false;
        }
        if (!hasLon1()) {
          
          return false;
        }
        if (!hasLat2()) {
          
          return false;
        }
        if (!hasLon2()) {
          
          return false;
        }
        if (!hasIgnoreTrains()) {
          
          return false;
        }
        if (!hasIgnoreSubte()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 13: {
              bitField0_ |= 0x00000001;
              lat1_ = input.readFloat();
              break;
            }
            case 21: {
              bitField0_ |= 0x00000002;
              lon1_ = input.readFloat();
              break;
            }
            case 29: {
              bitField0_ |= 0x00000004;
              lat2_ = input.readFloat();
              break;
            }
            case 37: {
              bitField0_ |= 0x00000008;
              lon2_ = input.readFloat();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              ignoreTrains_ = input.readBool();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              ignoreSubte_ = input.readBool();
              break;
            }
            case 58: {
              ensureMlkSet1StringIsMutable();
              mlkSet1String_.add(input.readBytes());
              break;
            }
            case 66: {
              ensureMlkSet2StringIsMutable();
              mlkSet2String_.add(input.readBytes());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required float lat1 = 1;
      private float lat1_ ;
      public boolean hasLat1() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public float getLat1() {
        return lat1_;
      }
      public Builder setLat1(float value) {
        bitField0_ |= 0x00000001;
        lat1_ = value;
        onChanged();
        return this;
      }
      public Builder clearLat1() {
        bitField0_ = (bitField0_ & ~0x00000001);
        lat1_ = 0F;
        onChanged();
        return this;
      }
      
      // required float lon1 = 2;
      private float lon1_ ;
      public boolean hasLon1() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public float getLon1() {
        return lon1_;
      }
      public Builder setLon1(float value) {
        bitField0_ |= 0x00000002;
        lon1_ = value;
        onChanged();
        return this;
      }
      public Builder clearLon1() {
        bitField0_ = (bitField0_ & ~0x00000002);
        lon1_ = 0F;
        onChanged();
        return this;
      }
      
      // required float lat2 = 3;
      private float lat2_ ;
      public boolean hasLat2() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public float getLat2() {
        return lat2_;
      }
      public Builder setLat2(float value) {
        bitField0_ |= 0x00000004;
        lat2_ = value;
        onChanged();
        return this;
      }
      public Builder clearLat2() {
        bitField0_ = (bitField0_ & ~0x00000004);
        lat2_ = 0F;
        onChanged();
        return this;
      }
      
      // required float lon2 = 4;
      private float lon2_ ;
      public boolean hasLon2() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public float getLon2() {
        return lon2_;
      }
      public Builder setLon2(float value) {
        bitField0_ |= 0x00000008;
        lon2_ = value;
        onChanged();
        return this;
      }
      public Builder clearLon2() {
        bitField0_ = (bitField0_ & ~0x00000008);
        lon2_ = 0F;
        onChanged();
        return this;
      }
      
      // required bool ignoreTrains = 5;
      private boolean ignoreTrains_ ;
      public boolean hasIgnoreTrains() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public boolean getIgnoreTrains() {
        return ignoreTrains_;
      }
      public Builder setIgnoreTrains(boolean value) {
        bitField0_ |= 0x00000010;
        ignoreTrains_ = value;
        onChanged();
        return this;
      }
      public Builder clearIgnoreTrains() {
        bitField0_ = (bitField0_ & ~0x00000010);
        ignoreTrains_ = false;
        onChanged();
        return this;
      }
      
      // required bool ignoreSubte = 6;
      private boolean ignoreSubte_ ;
      public boolean hasIgnoreSubte() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public boolean getIgnoreSubte() {
        return ignoreSubte_;
      }
      public Builder setIgnoreSubte(boolean value) {
        bitField0_ |= 0x00000020;
        ignoreSubte_ = value;
        onChanged();
        return this;
      }
      public Builder clearIgnoreSubte() {
        bitField0_ = (bitField0_ & ~0x00000020);
        ignoreSubte_ = false;
        onChanged();
        return this;
      }
      
      // repeated string mlkSet1String = 7;
      private com.google.protobuf.LazyStringList mlkSet1String_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureMlkSet1StringIsMutable() {
        if (!((bitField0_ & 0x00000040) == 0x00000040)) {
          mlkSet1String_ = new com.google.protobuf.LazyStringArrayList(mlkSet1String_);
          bitField0_ |= 0x00000040;
         }
      }
      public java.util.List<String>
          getMlkSet1StringList() {
        return java.util.Collections.unmodifiableList(mlkSet1String_);
      }
      public int getMlkSet1StringCount() {
        return mlkSet1String_.size();
      }
      public String getMlkSet1String(int index) {
        return mlkSet1String_.get(index);
      }
      public Builder setMlkSet1String(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureMlkSet1StringIsMutable();
        mlkSet1String_.set(index, value);
        onChanged();
        return this;
      }
      public Builder addMlkSet1String(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureMlkSet1StringIsMutable();
        mlkSet1String_.add(value);
        onChanged();
        return this;
      }
      public Builder addAllMlkSet1String(
          java.lang.Iterable<String> values) {
        ensureMlkSet1StringIsMutable();
        super.addAll(values, mlkSet1String_);
        onChanged();
        return this;
      }
      public Builder clearMlkSet1String() {
        mlkSet1String_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000040);
        onChanged();
        return this;
      }
      void addMlkSet1String(com.google.protobuf.ByteString value) {
        ensureMlkSet1StringIsMutable();
        mlkSet1String_.add(value);
        onChanged();
      }
      
      // repeated string mlkSet2String = 8;
      private com.google.protobuf.LazyStringList mlkSet2String_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureMlkSet2StringIsMutable() {
        if (!((bitField0_ & 0x00000080) == 0x00000080)) {
          mlkSet2String_ = new com.google.protobuf.LazyStringArrayList(mlkSet2String_);
          bitField0_ |= 0x00000080;
         }
      }
      public java.util.List<String>
          getMlkSet2StringList() {
        return java.util.Collections.unmodifiableList(mlkSet2String_);
      }
      public int getMlkSet2StringCount() {
        return mlkSet2String_.size();
      }
      public String getMlkSet2String(int index) {
        return mlkSet2String_.get(index);
      }
      public Builder setMlkSet2String(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureMlkSet2StringIsMutable();
        mlkSet2String_.set(index, value);
        onChanged();
        return this;
      }
      public Builder addMlkSet2String(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureMlkSet2StringIsMutable();
        mlkSet2String_.add(value);
        onChanged();
        return this;
      }
      public Builder addAllMlkSet2String(
          java.lang.Iterable<String> values) {
        ensureMlkSet2StringIsMutable();
        super.addAll(values, mlkSet2String_);
        onChanged();
        return this;
      }
      public Builder clearMlkSet2String() {
        mlkSet2String_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000080);
        onChanged();
        return this;
      }
      void addMlkSet2String(com.google.protobuf.ByteString value) {
        ensureMlkSet2StringIsMutable();
        mlkSet2String_.add(value);
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:colectivos.IndirectSearchRequest)
    }
    
    static {
      defaultInstance = new IndirectSearchRequest(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:colectivos.IndirectSearchRequest)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_colectivos_DirectSearchRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_colectivos_DirectSearchRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_colectivos_IndirectSearchRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_colectivos_IndirectSearchRequest_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016Requests.proto\022\ncolectivos\"x\n\023DirectSe" +
      "archRequest\022\014\n\004lat1\030\001 \002(\002\022\014\n\004lon1\030\002 \002(\002\022" +
      "\014\n\004lat2\030\003 \002(\002\022\014\n\004lon2\030\004 \002(\002\022\024\n\014ignoreTra" +
      "ins\030\005 \002(\010\022\023\n\013ignoreSubte\030\006 \002(\010\"\250\001\n\025Indir" +
      "ectSearchRequest\022\014\n\004lat1\030\001 \002(\002\022\014\n\004lon1\030\002" +
      " \002(\002\022\014\n\004lat2\030\003 \002(\002\022\014\n\004lon2\030\004 \002(\002\022\024\n\014igno" +
      "reTrains\030\005 \002(\010\022\023\n\013ignoreSubte\030\006 \002(\010\022\025\n\rm" +
      "lkSet1String\030\007 \003(\t\022\025\n\rmlkSet2String\030\010 \003(" +
      "\tB%\n\023eu.hellek.gba.protoB\016RequestsProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_colectivos_DirectSearchRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_colectivos_DirectSearchRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_colectivos_DirectSearchRequest_descriptor,
              new java.lang.String[] { "Lat1", "Lon1", "Lat2", "Lon2", "IgnoreTrains", "IgnoreSubte", },
              eu.hellek.gba.proto.RequestsProtos.DirectSearchRequest.class,
              eu.hellek.gba.proto.RequestsProtos.DirectSearchRequest.Builder.class);
          internal_static_colectivos_IndirectSearchRequest_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_colectivos_IndirectSearchRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_colectivos_IndirectSearchRequest_descriptor,
              new java.lang.String[] { "Lat1", "Lon1", "Lat2", "Lon2", "IgnoreTrains", "IgnoreSubte", "MlkSet1String", "MlkSet2String", },
              eu.hellek.gba.proto.RequestsProtos.IndirectSearchRequest.class,
              eu.hellek.gba.proto.RequestsProtos.IndirectSearchRequest.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
